- name:Demo on loops
  hosts: localhost
  tasks:
    -name: Print Fruit Name
     debug:
       msg: Fruit Name = {{item}}
     loop:
      - apple
      - banana
      - orange

- name: Print Fruit Name and Inventory Count
  debug:
    msg: Fruit Name = {{item.name}}  , Available Count = {{item.count}}
    loop:
     - {name: apple, count: 10}
     - {name: banana, count: 10}
     - {name: orange, count: 10}