- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: t3.micro
    security_group_id: sg-06e9dba4d9e1241fa
    image: my_ami_id
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         group_id: "{{ security_group_id }}"
         count: 1
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
           Name: ansible-role-check-instaance
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Run Role to Test
  hosts: launched
  become: True
  gather_facts: True
  tasks:
   - name: set the facts per host
     set_fact:
       INSTANCE_ID: "{{hostvars['localhost']}}"
   - name: Import role and terminate the instance
     block:
       - name: Import a role
         import_role:
           name: "{{role_name}}"
     always:
      - name : Terminate instance that were probably launched
       # Delegate_to:127.0.0.1
- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
