- name: Print Frontend
  ansible.builtin.debug:
    msg: Frontend

- name: Install Nginx
  ansible.builtin.yum:
       name: nginx
       state: installed

- name: Download and extract frontend
  include_role:
    name: common
    tasks_from: download

- name: Cleanup old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

#- name: Copy the frontend content to nginx path
#  ansible.builtin.copy:
#     src: /tmp/frontend-main/static/
#     dest: /usr/share/nginx/html/
#     remote_src: yes

#Note:in src and dest, ending / is very important when copying files

- name: Copy Roboshop Configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    notify: Restart nginx

- name: Start the nginx service
  #ignore_errors: "{{CHECK_MODE}}"
  ansible.builtin.systemd:
     name: nginx
     state: restarted
     enabled: yes
  ignore_errors: "{{CHECK_MODE}}"






