- name: Add Application user
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop project Application user
   register: app_user_register

- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Download and extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Cleanup old HTML content
  ansible.builtin.file:
    path: ""{{APP_LOCATION}}""
    state: absent

- name: Copy App Content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: """{{APP_LOCATION}}"
    remote_src: yes
  become_user: ""{{APP_USER}}""

