- name: Download and Extract  {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://nexus.roboshopInternal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: {{APP_LOCATION}}"
    remote_src: yes
  become_user: roboshop