- name: Configure Yum Repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
  name:
     - angularjs
     - gcc c++
  state: installed

- name: Setup App User , Download and Extract {{COMPONENT}} Content
  include_role:
     name: common
     tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop


#- name: Install NodeJS Dependencies
#  community.general.npm:
#    path: /home/roboshop{{COMPONENT}}
#  become_user: roboshop

- name: Setup SystemD
  include_role:
    name: common
    tasks_from: systemd
