- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

 name: Setup App User , Download and Extract {{COMPONENT}} Content
  include_role:
     name: common
     tasks_from: download

- name: Install python dependencies
  pip:
      requiurments: /home/roboshop/{{COMPONENT}}/requirments.txt
      executable: pip3

- name: Update USER ID in App Configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: 'uid'
    line: uid = {{APP_USER_REGISTER.uid}}

- name: Update GROUP ID in App Configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: 'gid'
    line: gid = {{APP_USER_REGISTER.gid}}

- name: Setup SystemD
  include_role:
    name: common
    tasks_from: systemd